<h1>Create a task</h1>
<br>
<form method="POST" action="" role="form" class="form-horizontal">
   <div class="form-group">
      <label class="control-label col-sm-2" for="name">Name</label>
      <div class="col-sm-10">
         <input type="text" name="name" class="form-control" placeholder="Enter name" required="required" />
      </div>
   </div>

   <div class="form-group">
      <label class="control-label col-sm-2" for="name">Deadline</label>
      <label class="control-label col-sm-2" for="name">To</label>
      <div class="col-sm-3">
         <input type="text" name="name" class="form_datetime form-control" placeholder="yyyy-mm-dd hh:ii" required="required" />
      </div>
      <label class="control-label col-sm-2" for="name">From</label>
      <div class="col-sm-3">
         <input type="text" name="name" class="form_datetime form-control" placeholder="yyyy-mm-dd hh:ii" required="required" />
      </div>
   </div>

   <div class="form-group">
      <label class="control-label col-sm-2" for="description">Description</label>
      <div class="col-sm-10">
         <textarea name="description" class="form-control" placeholder="Enter description"></textarea>
      </div>
   </div>

   <div class="text-right">
      <button type="submit" class="btn btn-success">Create</button>
   </div>
</form>
 
<script type="text/javascript">
    $(".form_datetime").datetimepicker({format: 'yyyy-mm-dd hh:ii'});
</script>  