<h1>Create a task</h1>
<br>
<form method="POST" action="<?php echo $this->serverUrl(true); ?>" role="form" class="form-horizontal">
   <div class="form-group">
      <label class="control-label col-sm-2" for="name">Name</label>
      <div class="col-sm-10">
         <input type="text" name="name" class="form-control" placeholder="Name..." required="required" />
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2" for="deadline">Deadline</label>
      <div class="col-sm-3">
         <div class="input-daterange">
            <input type="text" required="required" name="deadline" class="form-control" value="<?php echo date("Y-m-d"); ?>">
         </div>   
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2" for="duration">Duration in hours</label>
      <div class="col-sm-10">
         <input type="text" name="duration" class="form-control" placeholder="Duration..." required="required" />
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2">Priority level</label>
      <div class="col-sm-10">
         <select class="form-control" name="priority">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
         </select>
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2">Description</label>
      <div class="col-sm-10">
         <textarea name="description" class="form-control" placeholder="Description..."></textarea>
      </div>
   </div>
   <div class="text-right">
      <button type="submit" class="btn btn-success btnEasygoing">Create</button>
      <a class="btn btnEasygoing" href="<?php echo $_SERVER['HTTP_REFERER'] ?>">Back</a>
   </div>
</form>


<script type="text/javascript">
   $(function() {
      $('.input-daterange input').each(function() {
          $(this).datepicker({format: 'yyyy-mm-dd', autoclose:true});
      });
   });
</script>  