<h1>Add member to your project</h1>
<br>
<div class="input-group" style="float:left;">
   <input onkeyup="filterSearch();" type="text" id="search" class="form-control" placeholder="Search for..." aria-describedby="basic-addon1">
</div>
<br><br>
<hr>
<?php if(empty($users)): ?>
   <h2>No available user.<h2>
<?php else: ?>
   <form method="POST" action="<?php echo $this->serverUrl(true); ?>">
      <div class="container-fluid">
         <div class="row">
            <?php foreach ($users as $user) : ?>
               <div id="<?php echo $user->id; ?>" class="col-md-5 panel panel-default add-user" style="margin: 10px; padding: 10px;" firstname="<?php echo $user->firstName . ' ' . $user->lastName . ' ' . $user->username?>">
                  <img src="<?php echo $this->basePath('img/users/' . $user->filePhoto); ?>"
                  alt="<?php echo $this->escapeHtml($user->username); ?>" height=50 width=50
                  class="imgProject" />
                  <?php echo $user->firstName . ' ' . $user->lastName . ' (' . $user->username . ')'; ?>
                  <input hidden check="add" name="input-<?php echo $user->username; ?>" value="<?php echo $user->id; ?>" id="add-<?php echo $user->id; ?>" type="checkbox" style="float: right;">

                  <div class="checkbox" style="float: right;">
                     <label>
                        <input name="is-manager-<?php echo $user->id; ?>" id="<?php echo $user->id; ?>" class="is-manager" value="isManager" type="checkbox" style="float: right;"> Is manager 
                     </label>
                  </div>
               </div>
            <?php endforeach; ?>
         </div>
      </div>
      <br>
      <div style="float:right;"><button type="submit" class="btn btnEasygoing">Add member(s)</a></div>
   </form>
<?php endif; ?>
<div style="float:left;"><a class="btn btnEasygoing" href="<?php echo $_SERVER['HTTP_REFERER'] ?>">Back</a></div>

<script>
   
var nbSpecArray = [];
var MAX_SPEC_PER_USER = 5;
   
// Users filters
function filterSearch() {
   var text = $('#search').val();

   // For each divs in row
   $.each($('.row'), function(i, left) {
      $('div', left).each(function(i, div) {
         if($(div).attr('firstname').indexOf(text) > -1)
            $(div).show("fast");
         else
            $(div).hide("fast");
      });
   })
}

// Check if closest add checkbox is checked. If no we check it.
$('.is-manager').click(function (e) {
   var closestAddCheckbox = $('#add-' + $(this).attr('id'));
   
   if(!closestAddCheckbox.is(':checked'))
      $(this).closest('.add-user').click();

});
   
// Check checkbox when click on user div
$('.add-user').click(function (e) {
   if(!$(e.target).is(':checkbox') && !$(e.target).is('label') && !$(e.target).is('a') && !$(e.target).is(':text') && !$(e.target).is('.spe')) {
      
      var userId = $(this).attr('id');
      
      if($(this).hasClass('add-user-selected'))
      {
         $(this).removeClass('add-user-selected');
         nbSpecArray[userId] = 0;
         $(this).find('.spe').remove();
      }
      else
      {
         $(this).addClass('add-user-selected');
         
         nbSpecArray[userId] = 1;
         
         $(this).append('<div class="spe"><hr></div>')
         $(this).find('.spe').append('<div class="spe-input" style="float: left;"><input name="spe'+ userId +'[]" type="text" placeholder="Specialization" /></div>');
         $(this).find('.spe').append('<div style="float: right;"><a class="btn btnEasygoing add-spe">+</a></div>');
      }
      
      $(this).find('input[check=add]').prop("checked", !$(this).find('input[check=add]').prop("checked"));
   }
});
   
   
$(document).on("click", ".add-spe", function() {
   var divSpe = $(this).parent().parent().find('.spe-input');
   var userId = $(this).parent().parent().parent().attr('id');
   if(nbSpecArray[userId]++ >= MAX_SPEC_PER_USER)
      bootbox.alert('The max number of specializations for a user is ' + MAX_SPEC_PER_USER);
   else
      divSpe.append('<div style="margin-top: 5px"><input name="spe'+ userId +'[]" type="text" placeholder="Specialization" /></div>');
});
</script>
