<?php
   use Application\Utility\Priority;

   echo $this->headScript()
               ->prependFile($this->basePath() . '/js/board.contextmenu.js')
               ->prependFile($this->basePath() . '/js/board.dragdrop.js');

   function taskRendering($member, $task, $subTasks)
   {
      $priorityClass = "medium-priority";
      switch($task->priorityLevel)
      {
         case 1:
            $priorityClass = "high-priority";
            break;
         case 3:
            $priorityClass = "low-priority";
            break;
      }

      $nbSubTask = 0;

      $subTaskText = "<hr><div>";
      foreach($subTasks[$task->id] as $subTask)
      {
         $nbSubTask++;
         $subTaskText .= '<p>'.$subTask->name.'</p>';
      }
      $subTaskText .= "</div><hr>";

      if($nbSubTask == 0)
         $subTaskText = "";

      $taskContent =
         '<div id='.$member->email.$task->id.' task-id="'.$task->id.'" class="board-task '.$priorityClass.'">' .
            $task->name .
            "<br/>Duration: " . $task->durationInHours . "h" .
            $subTaskText .
            '<div class="task-details"><a href="/project/' . $task->project . '/taskDetails/' . $task->id . '">Details...</a></div>
         </div>';

      return $taskContent;
   }
?>

<script>
   $(document).ready(function() {
     // Init Bootstrap's tooltip on project's buttons.
     $('[data-toggle="tooltip"]').tooltip();
   });
</script>

<div class="board-header">
  <div class="board-header-section">
     <h1>Members</h1>
  </div>
  <div class="board-header-section">
     <h1>To do</h1>
  </div>
  <div class="board-header-section">
     <h1>Doing</h1>
  </div>
  <div class="board-header-section">
     <h1>Done</h1>
  </div>
</div>

<?php foreach ($members as $member): ?>
<div class="board" member-id="<?php echo $member->id; ?>">
   <div class="board-first-column" section="board-user"<?php echo ($creatorId == $member->id ? " data-toggle='tooltip' title='This user is the creator and super administrator of this project.'" : ($member->isAdmin ? " data-toggle='tooltip' title='This user is manager so he has management rights on the project.'" : "")); ?>>
   <?php
      if($creatorId == $member->id)
      {
   ?>
         <img style="float: left; height: 40px; margin-right: -58px; width: 40px;" draggable="false" src="/img/creator.png" >
   <?php
      }
      else if ($member->isAdmin)
      {
   ?>
         <img style="float: left; height: 40px; margin-right: -58px; width: 40px;" draggable="false" src="/img/manager.png" >
   <?php
      }
   ?>

      <img class="imgMember" draggable="false" src="<?php echo $this->basePath('img/users/'.$member->filePhoto); ?>">
      <h4 class="memberName"><?php echo $member->firstName . ' ' . $member->lastName; ?></h4>
      <span class="memberUsername"><?php echo $member->username; ?></span>
      <!-- Show member's specializations only if cookie is set. -->
      <div class="membersSpecializations"<?php echo ($showSpecializations ? "" : " style='display: none;'"); ?>>
        <hr/>
        <?php
         // Display every current member's specializations.
         foreach ($membersSpecializations as $memSpec)
         {
            if ($member->username == $memSpec["username"])
            {
              foreach ($memSpec["specializations"] as $spec)
              {
                 echo $spec . "<br/>";
              }
            }
         }

        ?>
     </div>
  </div>
  <div class="board-section" id="todo" section="TODO">
     <?php
     foreach($tasksForMember[$member->id] as $task)
     {
        if($task->state == "TODO")
        {
           echo taskRendering($member, $task, $subTasks);
        }
     }
     ?>
  </div>
  <div class="doing board-section" id="doing" section="DOING">
     <?php
     foreach($tasksForMember[$member->id] as $task)
     {
        if($task->state == "DOING")
        {
           echo taskRendering($member, $task, $subTasks);
        }
     }
     ?>
  </div>
  <div class="done board-section" id="done" section="DONE">
     <?php
     foreach($tasksForMember[$member->id] as $task)
     {
        if($task->state == "DONE")
        {
           echo taskRendering($member, $task, $subTasks);
        }
     }
     ?>
  </div>
</div>
<?php endforeach; ?>
