<?php use Application\Utility\Priority; ?>

<h1>Edit a task</h1>
<br>
<form method="POST" action="<?php echo $this->serverUrl(true); ?>" role="form" class="form-horizontal">
   <input hidden type="text" name="id" value="<?php echo $task->id; ?>">
   <div class="form-group">
      <label class="control-label col-sm-2" for="name">Name</label>
      <div class="col-sm-10">
         <input type="text" name="name" value="<?php echo $task->name; ?>" class="form-control" placeholder="Enter name" required="required" />
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2" for="deadline">Deadline</label>
      <div class="col-sm-3">
         <div class="input-daterange">
            <input type="text" required="required" name="deadline" class="form-control" value="<?php echo $task->deadLineDate; ?>">
         </div>
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2" for="duration">Duration in hours</label>
      <div class="col-sm-10">
         <input type="number" name="duration" value="<?php echo $task->durationsInHours; ?>" class="form-control" placeholder="Duration..." required="required" />
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2">Priority</label>
      <div class="col-sm-10">
         <select class="form-control" name="priority">
            <?php
               foreach(Priority::getConstants() as $value)
               {
                  echo '<option '.($task->priorityLevel == $value ? 'selected' : '').' value="'.$value.'">'.Priority::toString($value).'</option>';
               }
            ?>
         </select>
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2">Description</label>
      <div class="col-sm-10">
         <textarea name="description" class="form-control" placeholder="Enter description"><?php echo $task->description; ?></textarea>
      </div>
   </div>
   <div class="text-right">
      <a class="btn btnEasygoing" href="<?php echo $_SERVER['HTTP_REFERER'] ?>">Back</a>
      <button type="submit" class="btn btnEasygoing">Save changes</button>
   </div>

</form>

<script type="text/javascript">
   $(function() {
      $('.input-daterange input').each(function() {
          $(this).datepicker({format: 'yyyy-mm-dd', autoclose:true});
      });
   });
</script>
