<h1>Edit a task</h1>
<br>
<form method="POST" action="<?php echo $this->serverUrl(true); ?>" role="form" class="form-horizontal">
   <div class="form-group">
      <label class="control-label col-sm-2" for="name">Name</label>
      <div class="col-sm-10">
         <input type="text" name="name" value="<?php echo $task->name; ?>" class="form-control" placeholder="Enter name" required="required" />
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2">Deadline</label>
      <div class="col-sm-3">
         <div class="input-group input-daterange">
            <input type="text" name="startDate" class="form-control" value="<?php echo $task->deadLineDate; ?>">
            <span class="input-group-addon">to</span>
            <input type="text" name="deadlineDate" class="form-control" value="<?php echo $task->deadLineDate; ?>">
         </div>
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2">Priority</label>
      <div class="col-sm-10">
         <select class="form-control" name="priority">
            <?php 
               for($i = 1; $i <= 3; $i++)
               {
                  echo '<option '.($task->priorityLevel == $i ? 'selected' : '').' value"'.$i.'">'.$i.'</option>';
               }
            ?>
         </select>
      </div>
   </div>
   <div class="form-group">
      <label class="control-label col-sm-2">Description</label>
      <div class="col-sm-10">
         <textarea name="description" class="form-control" placeholder="Enter description"><?php echo $task->description; ?></textarea>
      </div>
   </div>
   <div class="text-right">
      <button type="submit" class="btn btn-success btnEasygoing">Save changes</button>
      <a class="btn btnEasygoing" href="<?php echo $_SERVER['HTTP_REFERER'] ?>">Back</a>
   </div>

</form>

<script type="text/javascript">
   $(function() {
      $('.input-daterange input').each(function() {
          $(this).datepicker({format: 'yyyy-mm-dd', autoclose:true});
      });
   });
</script>  