<h1>Dashboard - <?php echo $project->name; ?></h1>
<p>Description : <?php echo $project->description; ?></p>
<p>Durée : du <?php echo $project->startDate . ' au ' . $project->deadLineDate; ?></p>
<a href="<?php echo $this->serverUrl(true) . '/addTask'; ?>">Ajouter une tâche</a> -
<a href="<?php echo $this->serverUrl(true) . '/addMember'; ?>">Ajouter un membre</a>
<br><br>
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary active btnEasygoing">
    <input type="radio" name="options" id="option1" autocomplete="off" checked onchange="loadBoardViewMembers();"> View per members
  </label>
  <label class="btn btn-primary btnEasygoing">
    <input type="radio" name="options" id="option2" autocomplete="off" onchange="loadBoardViewTasks();"> View per tasks
  </label>
</div>
<p id="result"></p>
<div id="board-container"></div>
<br><br><hr><br>
<br>
<div class="container-fluid">
   <div class="row">
      <div class="col-md-6">
         <div class="panel panel-default">
            <div class="panel-heading">Tasks</div>
            <div class="panel-body">
               <?php foreach ($tasks as $task) : ?>
               <p><?php echo $task->name; ?></p>
               <?php endforeach; ?>
            </div>
         </div>
      </div>
      <div class="col-md-6">
         <div class="panel panel-default">
            <div class="panel-heading">Members</div>
            <div class="panel-body">
               <?php foreach ($members as $member) : ?>
               <p><?php echo $member->username; ?></p>
               <?php endforeach; ?>
            </div>
         </div>
      </div>
      <div class="col-md-6">
         <div class="panel panel-default">
            <div class="panel-heading">Test</div>
            <div class="panel-body">
               <pre>
               <?php foreach ($tasksForMember as $t) : ?>
               <p><?php var_dump($t); ?></p>
               <?php endforeach; ?>
               </pre>
            </div>
         </div>
      </div>
   </div>
</div>

<script>

function loadBoardViewMembers()
{
   $('#board-container').load(<?php echo '"'.$this->serverUrl(true) . '/boardViewMembers"'; ?>);
}
function loadBoardViewTasks()
{
   $('#board-container').load(<?php echo '"'.$this->serverUrl(true) . '/boardViewTasks"'; ?>);
}

loadBoardViewMembers();
</script>