<?php
   // Send Javascript variable with Zend.
   echo $this->headScript()->appendScript('// Indicate that the user is currently in the task page. Used in the board.websocket.js script.
                                           var isProjectPage = true;
                                           var projectId = "' . $project->id . '";');
   // Load websocket script.
   echo $this->headScript()
               ->prependFile($this->basePath() . '/js/board.websockets.js');

   // Return an HTML code rendering an event div, using for code factoring.
   function eventRendering($type, $event)
   {
      $eventContent =
         '<div class="eventElem" name="eventIn' . $type . '">
            <table class="eventTable">
               <tr>
                  <td rowspan=2><img class="eventImg" src="/img/events/' . $event->fileLogo . '" /></td>
                  <td><b>[' . date('d.m.Y', strtotime($event->date)) . ']</b></td>
               </tr>
               <tr>
                  <td><div class="eventMessage">' . $event->message . '</div></td>
               </tr>
            </table>
         </div>';

      return $eventContent;
   }
?>

<h1>Dashboard - <?php echo $project->name; ?></h1>
<hr>
<div class="projectHeader">
   <div class="leftPart">
      <p><u>Description</u> : <?php echo $this->escapeHtml($project->description); ?></p>
      <p><u>Duration</u> : from <?php echo date('d.m.Y', strtotime($project->startDate)) . ' to ' . date('d.m.Y', strtotime($project->deadLineDate)); ?></p>
      <p>
         <a href="<?php echo $this->serverUrl(true) . '/addTask'; ?>">Add a task</a><br/>
         <a href="<?php echo $this->serverUrl(true) . '/addMember'; ?>">Add members</a>
      </p>
   </div>

    <div class="rightPart">
        <div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs tabsMain" id="historicalTabs" role="tablist">
                <li role="presentation" class="active firstTab">
                   <a href="#all" aria-controls="all" role="tab" data-toggle="tab" style="outline: 0 none;">
                      All
                   </a>
                </li>
                <?php
                  // Dynamically add each projects' events types to the tabs list.
                  foreach ($eventsTypes as $type)
                  {
                ?>
                     <li role="presentation">
                        <a href="#<?php echo strtolower($type->type); ?>" aria-controls="<?php echo strtolower($type->type); ?>" role="tab" data-toggle="tab" style="outline: 0 none;">
                           <?php echo $type->type; ?>
                        </a>
                     </li>
                <?php
                  }
                ?>
                <li class="historicalTitle">Historical</li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content historicalTab">
               <div role="tabpanel" class="tab-pane fade in active" id="all">
               <?php
                  foreach ($events as $e)
                  {
                     echo eventRendering("All", $e);
                  }
                ?>
                </div>
                <?php
                  // Dynamically add each projects' events types content to the tabs list.
                  foreach ($eventsTypes as $type)
                  {
                ?>
                      <div role="tabpanel" class="tab-pane fade" id="<?php echo strtolower($type->type); ?>">
                         <?php
                           foreach ($events as $e)
                           {
                              if ($e->type == $type->type)
                              {
                                 echo eventRendering($e->type, $e);
                              }
                           }
                         ?>
                      </div>
                <?php
                   }
                ?>
            </div>
        </div>
    </div>
</div>

<br/><hr/>
<p id="result"></p>
<p class="boardButtons">
   <div class="btn-group" data-toggle="buttons">
      <label class="btn active btnEasygoing">
         <input type="radio" name="options" id="option1" autocomplete="off" checked onchange="loadBoardViewMembers();"> View per members
      </label>
      <label class="btn btnEasygoing">
         <input type="radio" name="options" id="option2" autocomplete="off" onchange="loadBoardViewTasks();"> View per tasks
      </label>
   </div>
</p>

<div id="board-alert-container"></div>
<div id="board-container"></div>

<br><br><hr><br>
<br>
<div class="container-fluid">
   <div class="row">
      <div class="col-md-6">
         <div class="panel panel-default">
            <div class="panel-heading">Tasks</div>
            <div class="panel-body">
               <?php foreach ($tasks as $task) : ?>
               <p><a href="<?php echo $this->serverUrl(true)."/editTask/".$task->id; ?>"><?php echo $task->name; ?></a><p>
               <?php endforeach; ?>
            </div>
         </div>
      </div>
      <div class="col-md-6">
         <div class="panel panel-default">
            <div class="panel-heading">Members</div>
            <div class="panel-body">
               <?php foreach ($members as $member) : ?>
               <p><?php echo $member->username; ?></p>
               <?php endforeach; ?>
            </div>
         </div>
      </div>
   </div>
</div>

<script>
    function loadBoardViewMembers() {
       $('#board-container').load(<?php echo '"'.$this->serverUrl(true) . '/boardViewMembers"'; ?>);
    }

    function loadBoardViewTasks() {
       $('#board-container').load(<?php echo '"'.$this->serverUrl(true) . '/boardViewTasks"'; ?>);
    }

    $(document).ready(function() {
        loadBoardViewMembers();

        // Enable tabbable tabs on the historical panel.
        $("#historicalTabs a").click(function(event) {
            event.preventDefault();
            $(this).tab("show");
        });
    });
</script>
