<?php
   // Return an HTML code rendering an event div, using for code factoring.
   function eventRendering($type, $event)
   {
      $eventContent =
         '<div class="eventElem" name="eventIn' . $type . '">
            <table class="eventTable">
               <tr>
                  <td rowspan=2><img class="eventImg" src="/img/events/' . $event->fileLogo . '" /></td>
                  <td><span class="newsFeedInfo">Posted on ' . date('d.m.Y', strtotime($event->date)) . ' by <u>' . $event->username . '</u></span></td>
               </tr>
               <tr>
                  <td><div class="eventMessage">' . $event->message . '</div></td>
               </tr>
            </table>
         </div>';

      return $eventContent;
   }
?>

<h1>Task details</h1>

<hr/>

<table class="taskDetailsTable">
   <tr>
      <td class="taskDetailsContentTable">
         <table>
            <tr>
               <td class="attributeName">Name</td>
               <td><?php echo $task->name; ?></td>
            </tr>
            <tr>
               <td class="attributeName">Deadline</td>
               <td><?php echo $task->deadLineDate; ?></td>
            </tr>
            <tr>
               <td class="attributeName">Duration</td>
               <td><?php echo $task->durationsInHours; ?>h</td>
            </tr>
            <tr>
               <td class="attributeName">Priority</td>
               <td>
                  <?php
                     $priority = ['High', 'Medium', 'Low'];
                     echo $priority[$task->priorityLevel - 1];
                  ?>
               </td>
            </tr>
            <tr>
               <td class="attributeName">Description</td>
               <td class="taskDescription"><?php echo (empty($task->description) ? "-" : $task->description); ?></td>
            </tr>
         </table>
      </td>
      <td class="newsFeed">
          <div>
              <!-- Nav tabs -->
              <ul class="nav nav-tabs tabsMain" id="historicalTabs" role="tablist">
                  <li role="presentation" class="active firstTab">
                     <a href="#all" aria-controls="all" role="tab" data-toggle="tab" style="outline: 0 none;">
                        All
                     </a>
                  </li>
                  <?php
                    // Dynamically add each tasks' events types to the tabs list.
                    foreach ($eventsTypes as $type)
                    {
                  ?>
                       <li role="presentation">
                          <a href="#<?php echo strtolower($type->type); ?>" aria-controls="<?php echo strtolower($type->type); ?>" role="tab" data-toggle="tab" style="outline: 0 none;">
                             <?php echo $type->type; ?>
                          </a>
                       </li>
                  <?php
                    }
                  ?>
                  <li class="historicalTitle">News Feed</li>
              </ul>

              <!-- Tab panes -->
              <div class="tab-content newsFeedTab">
                 <div role="tabpanel" class="tab-pane fade in active" id="all">
                    <?php
                       foreach ($events as $e)
                       {
                          echo eventRendering("All", $e);
                          echo eventRendering("All", $e);
                          echo eventRendering("All", $e);
                          echo eventRendering("All", $e);

                       }
                     ?>
                 </div>
                 <?php
                   // Dynamically add each tasks' events types content to the tabs list.
                   foreach ($eventsTypes as $type)
                   {
                 ?>
                       <div role="tabpanel" class="tab-pane fade" id="<?php echo strtolower($type->type); ?>">
                          <?php
                            foreach ($events as $e)
                            {
                               if ($e->type == $type->type)
                               {
                                  echo eventRendering($e->type, $e);
                               }
                            }
                          ?>
                       </div>
                 <?php
                    }
                 ?>
              </div>
          </div>
          <div class="input-group taskEventInput">
             <span class="input-group-addon" id="basic-addon1"><img id="imgType" class="eventSelectImg" src="/img/events/default.svg" /></span>
             <input class="form-control taskEventTextInput" placeholder="Enter a news..." type="text" />
             <div class="input-group-btn">
                <button id="tagBtn" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Select a tag... <span class="caret"></span></button>
                <ul id="tagMenu" class="dropdown-menu" role="menu">
                   <?php
                      // Dynamically add each tasks' events types content to the list.
                      foreach ($eventsTypes as $type)
                      {
                   ?>
                         <li><a href="#"><span id="spanType" img-type="<?php echo $type->fileLogo; ?>"><?php echo $type->type; ?> </span></a></li>
                   <?php
                      }
                   ?>
                </ul>
                <button class="btn btn-default" type="button">Post!</button>
             </div>
         </div>
      </td>
   </tr>
</table>

<hr/>

<a class="btn btnEasygoing" href="<?php echo $_SERVER['HTTP_REFERER'] ?>">Back</a>

<script>
   $(document).ready(function() {
      $('.dropdown-menu a').on('click', function() {
         $('.dropdown-toggle').html($(this).html() + '<span class="caret"></span>');

         $("#imgType").attr("src", "/img/events/" + $(this).find("#spanType").attr("img-type"));
      });
   });
</script>
