<h1 class="pageTitle" align = "left">Help</h1>
<hr/>

<p>
<h4 class="pageTitle" align = "left"> EasyGoing</h4>
<li>What is EasyGoing ?</li>

  <pre>
    Easygoing is a project management site.<br/>
    it allows you to manage your projects easily due to the various features it offers.
  </pre>

<li>Features</li>
<pre>
  <li type = "circle"><b>Divide projects into tasks </b>
    EasyGoing allows to create projects and divide them into tasks and subtasks. <br/>
    Divide and rule, this allows you to work and move strategically in your project.
  </li>
  <li type = "circle"><b>Assign tasks </b>
    the administrator of a project (the one who creates it or has been appointed as administrator)<br/>
    can add members having an account to the project . A dashboard provided allows to assign <br/>
    tasks to different members of the project just by a drag and drop. A task<br/>
    is dragged to a member that it would like to assign. It can again be moved to another<br/>
    Member. This action can be made by any member of the project.
  </li>
  <li type = "circle"><b>Project Status</b>
    A dashboard provided allows to specify the status of a task or sub task using<br/>
    three columns with the following respective values: Not started, in progress, complete.<br/>
    it is even possible to see the status of the various members of a project group in a dashbord.
  </li>
  <li type = "circle"><b>Publishing system</b>
    it allows all group members to be informed on the various activities related<br/>
    to the project. To do this, there is a space where members can post comments<br/>
    and receive events <br/>
  </li>
</pre>
<li>How to use EasyGoing ?</li>
<pre>
    Tutorials are available on each main page to help you understand how this tool works
</pre>
<li>Limits</li>
<pre>
    Currently, projects can only be planned on the web platform. There is not yet<br/>
    a version compatible with smartphones.
</pre>
</p>
