<h1>Help</h1>
<hr/>
<br/>
<b>What is EasyGoing ?</b>
<div class="helpExplanations">
   Easygoing! is a project management website.<br/>
   It allows you to easily manage your projects due to the various features it offers.
</div>

<b>Features</b>
<div class="helpExplanations">
   <ul>
     <li type = "circle"><b>Divide Projects into Tasks</b><br/>
       EasyGoing! allows you to create projects and divide them into tasks and subtasks.<br/>
       Divide and rule your own project so you can work and think strategically about it!
     </li>
     <li type = "circle"><b>Assign Tasks</b><br/>
       The project's administrators (the user who created it and the ones which was graded as administrators)
       can add other existing users to the project.<br/>
       In the project page you can access a dashboard, which allows you to assign
       tasks to different members just by dragging and droping them as many times as you like!
       Members can only move tasks that belong to them, while administrators can move any task they want.
     </li>
     <li type = "circle"><b>Tasks Status</b><br/>
       The provied project's dashboard allows you to specify the status of a task or subtask with the
       following respective values: <i>To do</i>, <i>Doing</i> and <i>Done</i>.
     </li>
     <li type = "circle"><b>Publication System</b><br/>
       This system allows all project's members to be informed of the project's historical.<br/>
       It also allows users to post comments with tags (<i>Info</i>, <i>Warning</i> and <i>Error</i>) separately on each task's details page.
     </li>
  </ul>
</div>

<b>How to use EasyGoing ?</b>
<div class="helpExplanations">
    Tutorials are available on each important page to help you understanding how is EasyGoing! working.
</div>

<b>Limits</b>
<div class="helpExplanations">
    Projects can currently only be planned on the web platform ; there is no smartphone application existing yet.
</div>
