<style>
.img-center {
   margin: 0 auto;
   width: 100px;
}
</style>

<!-- Introduction Row -->
<div class="row" style="margin-top: -45px">
   <div class="col-lg-12">
       <h1 class="page-header aboutTitle">About Us
           <small>Nice to Meet You!</small>
       </h1>
       <p>
          Easygoing started as a school semester project during which we also had a lot of other projects and works to do.<br/>
          It was a good experience for us because of the difficulty to manage several works at the same time, but we are proud to announce it was a success!
       </p>
       <p>
          We discussed a lot and decided to create a projects management website.<br/>
          After a few months we are now excited to show you <i>our</i> own project ; feel free to use it at your convenience! &#9829;
       </p>
   </div>
</div>

<hr/>

<!-- Team Members Row -->
<h2>Our Team</h2>
   <div class="aboutUsersWrapper">
      <div class="col-lg-4 col-sm-6 text-center aboutUser">
          <img class="img-circle img-responsive img-center" src="/img/about/miguel.png" alt="">
          <h3>Miguel Santamaria<br/>
              <small>Project Manager and Developer</small>
          </h3>
          <p>He led the team, designed the website and developed a lot of different things like the projects list, the websockets part, and other pages.</p>
      </div>
      <div class="col-lg-4 col-sm-6 text-center aboutUser">
          <img class="img-circle img-responsive img-center" src="/img/about/raphael.png" alt="">
          <h3>Raphaël Racine<br/>
              <small>Database Manager and Developer</small>
          </h3>
          <p>The only and true database creator and manager! He also developed all the pretty tutorial parts of the website.</p>
      </div>
      <div class="col-lg-4 col-sm-6 text-center aboutUser">
          <img class="img-circle img-responsive img-center" src="/img/about/thibaud.png" alt="">
          <h3>Thibaud Duchoud<br/>
              <small>Developer</small>
          </h3>
          <p>This is our project's <i>dashboard</i> expert! He put all his love and know-how in this task so you can enjoy a really ergonomic page.</p>
      </div>
      <div class="col-lg-4 col-sm-6 text-center aboutUser">
          <img class="img-circle img-responsive img-center" src="/img/about/karim.png" alt="">
          <h3>Karim Ghozlani<br/>
              <small>Developer</small>
          </h3>
          <p>One of our two users' masters! He managed to give you a securized access to the website and worked with cookies! No, not the ones you can eat...</p>
      </div>
      <div class="col-lg-4 col-sm-6 text-center aboutUser">
          <img class="img-circle img-responsive img-center" src="/img/about/vanessa.png" alt="">
          <h3>Michelle Vanessa Meguep Sakam<br/>
              <small>Developer</small>
          </h3>
          <p>Our second users' master! Thanks to her, you can register in our website and get some help from the well-named page.</p>
      </div>
   </div>

<hr/>

<h2>GitHub</h2><br/>
<p>
   Feel free to follow us on <a href="https://github.com/edri/EasyGoing">GitHub</a>!
</p>

<br/>
