<style>
.img-center {
   margin: 0 auto;
   width: 100px;
}
</style>

<!-- Introduction Row -->
<div class="row" style="margin-top: -45px">
   <div class="col-lg-12">
       <h1 class="page-header">About Us
           <small>It's Nice to Meet You!</small>
       </h1>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, explicabo dolores ipsam aliquam inventore corrupti eveniet quisquam quod totam laudantium repudiandae obcaecati ea consectetur debitis velit facere nisi expedita vel?</p>
   </div>
</div>

<!-- Team Members Row -->
<div class="row">
   <div class="col-lg-12">
       <h2 class="page-header">Our Team</h2>
   </div>
   <div class="col-lg-4 col-sm-6 text-center">
       <img class="img-circle img-responsive img-center" src="http://placehold.it/100x100" alt="">
       <h3>Miguel Santamaria
           <small>Job Title</small>
       </h3>
       <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
   </div>
   <div class="col-lg-4 col-sm-6 text-center">
       <img class="img-circle img-responsive img-center" src="http://placehold.it/100x100" alt="">
       <h3>Thibaud Duchoud
           <small>Job Title</small>
       </h3>
       <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
   </div>
   <div class="col-lg-4 col-sm-6 text-center">
       <img class="img-circle img-responsive img-center" src="http://placehold.it/100x100" alt="">
       <h3>Raphaël Racine
           <small>Job Title</small>
       </h3>
       <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
   </div>
   <div class="col-lg-4 col-sm-6 text-center">
       <img class="img-circle img-responsive img-center" src="http://placehold.it/100x100" alt="">
       <h3>Karim Ghozlani
           <small>Job Title</small>
       </h3>
       <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
   </div>
   <div class="col-lg-4 col-sm-6 text-center">
       <img class="img-circle img-responsive img-center" src="http://placehold.it/100x100" alt="">
       <h3>Michelle Vanessa Meguep Sakam
           <small>Job Title</small>
       </h3>
       <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
   </div>
</div>