<h1>Tests pour le tutoriel...</h1>

<script type="application/javascript">
    
    var tutoData;
    var current = 0;

    var nextTutorial = function() {
        
        var d = tutoData[current];
        
        // Affichage du tutoriel sur la page
        $("div[role=tutorial][id != " + d.div + "]").fadeOut();       
        $("div[role=tutorial][id = " + d.div + "]").fadeIn();
        
        current = (current + 1) % tutoData.length;
        
    };

    Tutorial('projects', function(data) {
        tutoData = data;
        nextTutorial();
    });
    
</script>

<div id="salut" role='tutorial' hidden=true>
    <img src="/img/tuto.png">Coucou mon ami</img>
    <a href="#" onClick="nextTutorial()">Next</a>
</div>

<h2>Ici s'affiche le tutoriel 1</h2>

<div id="bonjour" role='tutorial' hidden=true>
    <img src="/img/tuto.png">Coucou mon ami</img>
    <a href="#" onClick="nextTutorial()">Next</a>
</div>


<h2>Ici s'affiche le tutoriel 2</h2>

<div id="coucou" role='tutorial' hidden=true>
    <img src="/img/tuto.png">Coucou mon ami</img>
    <a href="#" onClick="nextTutorial()">Next</a>
</div>





