<?php
   echo $this->doctype();
?>

<?php
   use Zend\Session\Config\SessionConfig;
   use Zend\Session\Container;

   $sessionUser = new container('user');
	$controller = $this->controllerName();
?>

<html lang="en">
   <head>
      <meta charset="utf-8">
      <?php echo $this->headTitle('EasyGoing')->setSeparator(' - ')->setAutoEscape(false) ?>

      <?php echo $this->headMeta()
         ->appendName('viewport', 'width=device-width, initial-scale=1.0')
         ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
      ?>

      <?php
         // Styles
      	echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'))
                     ->prependStylesheet($this->basePath() . '/css/style.css')
                     ->prependStylesheet($this->basePath() . '/css/libraries/bootstrap-datepicker.css')
                     ->prependStylesheet($this->basePath() . '/css/libraries/bootstrap-datetimepicker.min.css')
                     ->prependStylesheet($this->basePath() . '/css/libraries/bootstrap.min.css')
                     ->prependStylesheet($this->basePath() . '/css/libraries/bootstrap-switch.min.css')
                     ->prependStylesheet($this->basePath() . '/css/libraries/contextmenu.css');
         // Scripts
			echo $this->headScript()
                     ->prependFile($this->basePath() . '/js/utilities.js')
                     ->prependFile($this->basePath() . '/js/libraries/bootbox.js')
                     ->prependFile($this->basePath() . '/js/libraries/jquery.ui.position.js')
                     ->prependFile($this->basePath() . '/js/libraries/jquery.contextmenu.js')
                     ->prependFile($this->basePath() . '/js/libraries/bootstrap-datepicker.js')
                     ->prependFile($this->basePath() . '/js/libraries/bootstrap.min.js')
                     ->prependFile($this->basePath() . '/js/libraries/bootstrap-switch.min.js')
                     ->prependFile($this->basePath() . '/js/libraries/jquery.min.js');

            // If user want tutorials
            if($sessionUser->wantTutorial)
                echo $this->headScript()->prependFile($this->basePath() . '/js/tuto.js');
        ?>
        <script>
           $(document).ready(function() {
             // Indicate if the header is currently hidden (true) or not (false).
             var isHeaderHidden = false;

             // Simulate a scroll on the main content's panel when the user move
             // the mouse's wheel with the cursor out of the panel.
             // First we need to detect a wheel's moving.
             $(window).on('wheel mousewheel DOMMouseScroll', function (e) {
                // Check if the main content's panel have a scroll bar ; in other
                // words, check if the panel's scrolling's height is larger than
                // the panel's height.
                var isScrollBarExisting = (document.getElementById("mainContent").scrollHeight > $("#mainContainer").height());
                // Get mouse wheel's delta (the amount of "strength" ; can be positive
                // or negative).
                var oEvent = e.originalEvent, delta  = oEvent.deltaY || oEvent.wheelDelta;

                // Simulate the scroll only if the user's cursor is out of the main
                // content's panel and if there is a scrollbar.
                if (!$("#mainContent").is(":hover") && isScrollBarExisting)
                {
                   // If there is a delta, simulate the main content's panel's scrolling.
                   if (delta) {
                      $("#mainContent").scrollTop($("#mainContent").scrollTop() + 30 * (delta < 0 ? -1 : 1));
                   }
                }
                // If the header is hidden and there is no scrollbar (can occur when the
                // scrollzone has exactly the same height as the header) and the user
                // scrolled up, show it.
                else if (delta < 0 && !isScrollBarExisting && isHeaderHidden)
                {
                   $("#header").slideDown(300, function() {
                      isHeaderHidden = false;
                   });
                   $("#mainContainer").removeClass("noPaddingTop");
                }
             });

             // Occurs when the user scrolled the main content.
             $("#mainContent").on("scroll", function () {
                // There is three cases:
                //   1. The header is shows and the user scrolled down
                //         => we need to hide the header (to gain some space on the page).
                //   2. The header is hidden and the user scrolled down
                //         => nothing to do, just let the system scrolls the element.
                //   3. The header is hidden and the user scrolled to the maximum top
                //         => we need to show again the header.
                // CASE 1
                if ($(this).scrollTop() > 0) {
                   if (!isHeaderHidden) {
                      $("#header").slideUp(300, function() {
                        isHeaderHidden = true;
                      });
                      $("#mainContainer").addClass("noPaddingTop");
                      // The first scroll doesn't really scroll the content, because
                      // of the header's hidding.
                      $(this).scrollTop(1);
                   }
                }
                // CASE 3
                else {
                   if (isHeaderHidden) {
                      if (!$("#header").is(":visible")) {
                         $("#header").slideDown(300, function() {
                            isHeaderHidden = false;
                         });
                         $("#mainContainer").removeClass("noPaddingTop");
                      }
                   }
                }
             });
           });
        </script>
    </head>

    <body>
   	<div class="header" id="header">
   	   <div class="container">
   	      <a href="/" class="title" style="outline: 0 none;"><img class="logo" src="<?php echo $this->basePath('img/title.svg'); ?>" height=70 /></a>
            <div class="headerLinks">
   		  <?php
   		  	if ($sessionUser && $sessionUser->connected)
   			{
   		  ?>
   			   <a href="<?php echo $this->basePath('projects'); ?>" class="btn btnHeader<?php if ($controller == "Application\Controller\Project" || $controller == "Application\Controller\Projects") echo "Selected" ?> btn-link" type="button">Projects</a>
               <a href="<?php echo $this->basePath('edit'); ?>" class="btn btnHeader<?php if ($controller == "Application\Controller\User") echo "Selected" ?> btn-link" type="button">Account</a>
           <?php
            }
           ?>
               <a href="<?php echo $this->basePath('about/help'); ?>" class="btn btnHeader<?php if ($controller == "Application\Controller\About") echo "Selected" ?> btn-link" type="button">Help</a>
            </div>
           <?php
    		  	if ($sessionUser && $sessionUser->connected)
    			{
    		  ?>
   		      <div class="headerRight">
   		         <span class="loginInformation">Logged in as <b> <?php echo $sessionUser->username; ?> </b></span>
   		         <a href="/logout" id="btnLogout" class="btn btnLogout btnEasygoing" type="button">Logout</a>
   		      </div>
   		 <?php } ?>
   	   </div>
   	</div>
      <div class="mainContainer" id="mainContainer">
      	<div class="container content mainContent" id="mainContent">
      		<?php echo $this->content; ?>
         </div> <!-- /container -->
      </div>
      <div class="footerWrapper">
   		<div class="container footer">
   			EasyGoing! &copy; 2015
   			<a href="/about" class="about">About</a>
         </div>
      </div>
      <?php echo $this->inlineScript() ?>
    </body>
</html>
