<form action="/registration" class="form-horizontal" method="POST" role="form">
	<div class="form-group">
        <label class="control-label col-sm-2" for="username">Username *</label>
        <div class="col-sm-10">
           <input type="text" name="username" class="form-control"  required="required"
					 placeholder="Enter username" value="<?php if (isset($username)) echo $this->escapeHtml($username); ?>
					 "/>
        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="lastname">Last name </label>
        <div class="col-sm-10">
           <input type="text" name="lname" class="form-control"
					 placeholder="last name"  value="<?php if (isset($lname)) echo $this->escapeHtml($lname); ?>" />

        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="firstname">First name </label>
        <div class="col-sm-10">
           <input type="text" name="fname" class="form-control"
					 placeholder="firstname"  value="<?php if (isset($fname)) echo $this->escapeHtml($fname); ?>" />
        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="password1">Password *</label>
        <div class="col-sm-10">
           <input type="password" name="password1" class="form-control" required="required" value="<?php if (isset($password1)) echo $this->escapeHtml($password1); ?>"/>
        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="password2">Repeat Password *</label>
        <div class="col-sm-10">
           <input type="password" name="password2" class="form-control" required="required" value="<?php if (isset($password2)) echo $this->escapeHtml($password2); ?>"/>
        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email* </label>
        <div class="col-sm-10">
           <input type="email" name="email" class="form-control" required="required"
					 placeholder="Enter valid email"   value="<?php if (isset($email)) echo $this->escapeHtml($email); ?>"/>
        </div>
     </div>
     <div>
       <label class="control-label col-sm-2" for="picture">Picture </label>
       <div>
        <input id="input-21" type="file" accept="image/*" class="file-loading" name="picture" value="10485760" >
          <script>
          $(document).on('ready', function() {
              $("#input-21").fileinput({
                  previewFileType: "image",
                  browseClass: "btn btn-success",
                  browseLabel: "Pick Image",
                  browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
                  removeClass: "btn btn-danger",
                  removeLabel: "Delete",
                  removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
                  uploadClass: "btn btn-info",
                  uploadLabel: "Upload",
                  uploadIcon: "<i class=\"glyphicon glyphicon-upload\"></i> "
              });
          });
          </script>
       </div>
   </div>
   <div>
     <label class="checkbox-inline"><input type="checkbox" value="">Tutorial</label>
   </div>

	 <div class="form-group formSending" >
		<label class="control-label col-sm-2" for="create"></label>
		<div class="col-sm-10">
				<span class="mandatoryFields">* Mandatory fields</span>
				<button class="btnCreate btn btnEasygoing" id="create" name="create" onClick="location.href='/projects/add';">create</button>
		</div>
</div>
</form>
