<div class="registrationDiv">
   <form action="/edit" class="form-horizontal" enctype="multipart/form-data" method="POST" role="form">
   <h2>
       <img class="accountImg" src="/img/users/<?php echo $picture; ?>" />
       Your account
   </h2>

   <hr/>

   <?php
      if (isset($result))
      {
         if ($result == "ok" || $result == "nothingChanged")
         {
   ?>
            <div class="panel panel-success">
               <div class="panel-heading">
            <?php
               if ($result == "ok")
               {
            ?>
                  Yay, your account has been successfully edited!
            <?php
               }
               else
               {
            ?>
                  Nothing changed :)
            <?php
               }
            ?>
               </div>
            </div>
   <?php
         }
         else
         {
   ?>
            <div class="panel panel-danger">
                <div class="panel-heading">
                   <?php
                      switch($result)
                      {
                        case "errorFieldEmpty":
                           echo "Please fill all mandatory fields and check that your username does not contain spaces.";
                           break;
                        case  "errorPasswordsDontMatch":
                           echo "The passwords you entered don't match, please retry.";
                          break;
                        case  "errorEmailInvalid":
                          echo "Please use a valid email format.";
                          break;
                        case "errorEmailAlreadyExists":
                           echo "The email address you entered already exists, please retry.";
                           break;
                        case "errorPictureSize":
                          echo "The picture you're trying to upload is too large, please retry.";
                          break;
                        case "errorPictureType":
                        case "errorPictureExtension":
                          echo "Please upload a file, which extension is allowed.";
                          break;
                        case  "errorPicture":
                          echo "Something is wrong with the file you're trying to upload, please retry.";
                          break;
                        case  "errorFilesUpload":
                          echo "Something wrong happend when uploading the picture, please retry.";
                          break;
                        case  "errorDatabaseAdding":
                          echo "Something wrong happend when creating the account, please retry.";
                          break;
                        default:
                           echo "An error occured, please retry.";
                           break;
                      }
                   ?>
                </div>
            </div>
   <?php
         }
     }
   ?>

   <div class="input-group">
     <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
     <input type="text" name="username" class="form-control"  disabled="disabled"
        value="<?php echo $this->escapeHtml($username); ?>"/>
   </div>

   <div class="input-group">
     <span class="input-group-addon"><span class="glyphicon glyphicon-tag"></span></span>
     <input type="text" name="fname" class="form-control" required="required" maxlength=30
         placeholder="Your First Name" value="<?php echo $this->escapeHtml($fName); ?>" />
   </div>

   <div class="input-group">
     <span class="input-group-addon"><span class="glyphicon glyphicon-tag"></span></span>
     <input type="text" name="lname" class="form-control" required="required" maxlength=30
        placeholder="Your Last Name" value="<?php echo $this->escapeHtml($lName); ?>" />
   </div>

   <div class="input-group">
     <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
     <input type="password" name="password1" class="form-control"
        placeholder="Enter new password (or leave the field empty if you don't want to change)" />
   </div>

   <div class="input-group">
     <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
     <input type="password" name="password2" class="form-control"
        placeholder="Retype password to confirm (or leave the field empty if you don't want to change)" />
   </div>

   <div class="input-group">
     <span class="input-group-addon">@</span>
     <input type="email" name="email" class="form-control" required="required" maxlength=64
        placeholder="Enter a valid email address" value="<?php if (isset($email)) echo $this->escapeHtml($email); ?>"/>
   </div>

   <hr/>

   <div class="form-group registrationPicture">
    <label class="control-label col-sm-2" for="picture">Picture</label>
    <div class="col-sm-10">
         <p class="logoInformation">Priorize a <b>squared</b> picture - Maximum size of <b>2 MB</b> - Allowed extensions: <b>"jpeg", "jpg" or "png"</b>.</p>
      <input type="hidden" name="MAX_FILE_SIZE" value="5242880" />
      <input id="picture" name="picture" type="file" />
    </div>
   </div>

   <div class="form-group registrationParameters">
     <label class="control-label col-sm-2" for="tutorial">Tutorial</label>
     <div class="col-sm-1">
         <input class="registrationChk"<?php if (isset($wantTutorial) && $wantTutorial) echo " checked='checked'"; ?> type="checkbox" name="tutorial" />
     </div>

     <label class="control-label col-sm-3" for="tutorial">Email Notifications</label>
     <div class="col-sm-1">
         <input class="registrationChk"<?php if (isset($wantNotifications) && $wantNotifications) echo " checked='checked'"; ?> type="checkbox" name="notifications" />
     </div>
   </div>

   <hr/>

   <input class="btnCancelRegistration btn btnEasygoing" id="cancel" name="cancelButton" onClick="location.href='/projects';" type="button" value="Back" />
   <input class="btnCreate btn btnEasygoing" id="create" name="update" type="submit" value="Edit account" />
</div>
</form>
