<h1>Welcome to EasyGoing !</h1>

</br>

<?php
   if (isset($successfulRegistration) && $successfulRegistration)
   {
?>
      <div class="panel panel-success error">
         <div class="panel-heading">
            Yay, you successfully registered! You can now sign in.
         </div>
      </div>
<?php
   }
?>
<?php
    if (isset($error))
    {
?>
        <div class="panel panel-danger error">
            <div class="panel-heading">
                <p> Login failed </p>
            </div>
        </div>
<?php
    }
?>

<form class="form-inline" method="POST">

  <div class="form-group">
    <label class="sr-only" for="exampleInputEmail3">Username</label>
    <input name = "username" type="name" class="form-control" id="exampleInputEmail3" placeholder="Username">
  </div>

  <div class="form-group">
    <label class="sr-only" for="exampleInputPassword3">Password</label>
    <input name= "password" type="password" class="form-control" id="exampleInputPassword3" placeholder="Password">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox" name = "checkbox" value ="1"> Remember me
    </label>
  </div>
  <button type="submit" class="btn btn-default">Sign in</button>
</form>

</br>

<p>
  <a type="button" class="btn btn-primary btn-lg btnEasygoing" href="/registration" >Subscribe</a>
</p>
