<script>
   $(document).ready(function() {
   <?php
      if (!isset($error) && (!isset($successfulRegistration) || !$successfulRegistration))
      {
   ?>
         $("#homePageTitle").fadeIn("slow", function() {
            $("#homePageLogIn").fadeIn("slow", function() {
               $("#homePageLogo").addClass("homePageLogoMoved");
            });
         });
   <?php
      }
      else
      {
   ?>
         $("#homePageTitle").show();
         $("#homePageLogIn").show();
         $("#homePageLogo").css("transition", "none").addClass("homePageLogoMoved");
   <?php
      }
   ?>
      });
</script>

<div class="homePage">
   <div class="homePageTitle" id="homePageTitle">
      <img class="homePageLogo" id="homePageLogo" src="/img/logo.svg" />
      <img src="/img/homeTitle.svg" />
   </div>

   <div class="homePageLogIn" id="homePageLogIn">
      <form action="/" class="form-horizontal" method="POST" role="form">
       <h2>
          <img class="loginImg" src="/img/users/default.png" />
          Sign In
       </h2>

        <hr/>

        <div class="formInput loginUsername">
          <label for="username">Username</label>
          <input type="text" name="username" class="form-control"  required="required"
     			 placeholder="Enter username" value="<?php if (isset($username)) echo $this->escapeHtml($username); ?>"/>
        </div>

        <div class="formInput">
          <label for="password1">Password</label>
          <a class="passwordForgotten" href="/passwordforgotten" tabindex="-1"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span> Forgot Password?</a>
          <input type="password" name="password" class="form-control" placeholder="Type password" required="required" />
        </div>

        <div class="loginParameters">
           <div class="checkbox rememberMe">
              <label><input class="rememberMeChk" name="checkbox" type="checkbox" value ="1" />Remember me</label>
           </div>
           <input class="btn btnEasygoing btnSignIn" type="submit" value="Log In" />
        </div>

        <?php
          if (isset($successfulRegistration) && $successfulRegistration)
          {
        ?>
             <div class="panel panel-success">
                 <div class="panel-heading">
                    Yay, you successfully registered! You can now log in.
                 </div>
             </div>
        <?php
          }
        ?>
        <?php
            if (isset($error))
            {
        ?>
                <div class="panel panel-danger">
                    <div class="panel-heading">
                       Login failed, please retry.
                    </div>
                </div>
        <?php
            }
        ?>

        <hr/>

        <div class="register">
           Don't have an account? No worry just <a href="/registration"><b>click here</b></a> to register!
        </div>
      </form>
   </div>
</div>
