<?php
   if (isset($successfulMail) && $successfulMail)
   {
?>
      <div class="panel panel-success error">
         <div class="panel-heading">
            Yay, a new password has been sent to  <?php if (isset($email)) echo $this->escapeHtml($email); ?>
         </div>
      </div>
<?php
   }
?>

<?php
   // if there was an error when creating the posted account, display it.
   if (isset($error))
   {
?>
        <div class="panel panel-danger error">
           <div class="panel-heading">
           <?php
                 switch($error)
                 {              
            case  "errorEmailDoesNotExist":
              echo "The given email address does not exist.";
              break;            
                  default:
               echo "An error occured, please retry.";
                     break;
            }
            ?>
         </div>
      </div>
<?php
   }
?>
<div>
	<h3> Please enter your email address, in order to send you a new password</h3>
	</br>
	</br>
	</br>
</div>	
<form action="/passwordforgotten" class="form-horizontal" method="POST" role="form">
   <div class="form-group">
     <label class="control-label col-sm-2" for="email">Email </label>
     <div class="col-sm-10">
        <input type="email" name="email" class="form-control" required="required"
   			 placeholder="Enter your email address"  />
     </div>
   </div>
   <p>
  <input class="btnCreate btn btnEasygoing" id="update" name="update" type="submit" value="Send new password">
</p>
<form/>