<div class="passwordForgottenDiv">
   <h3>Oh, it seems you lost your password... Don't worry!</h3>

   <hr class="passForgHr"/>

<?php
   if (isset($result))
   {
      if ($result == "ok")
      {
?>
         <div class="panel panel-success">
            <div class="panel-heading">
               A new password has been sent to '<?php echo $this->escapeHtml($email); ?>'.
            </div>
         </div>
<?php
      }
      else
      {
?>
         <div class="panel panel-danger">
            <div class="panel-heading">
<?php
         switch($result)
         {
            case "errorEmailDoesNotExist":
               echo "The email address you entered doesn't exist.";
               break;
            case "errorMailNotSent":
               echo "We couldn't send you an e-mail... Please retry in a while.";
               break;
         }
?>
            </div>
         </div>
<?php
      }
   }
?>

   <form action="/passwordforgotten" class="form-horizontal" method="POST" role="form">
      Please enter your email address so we can send you a new password
      <div class="input-group">
        <span class="input-group-addon">@</span>
        <input tabindex="1" type="email" name="email" class="form-control" required="required" maxlength=64
           placeholder="Enter valid email address" />
      </div>

      <input tabindex="3" class="btnCancelForgPass btn btnEasygoing" id="cancel" name="cancelButton" onClick="location.href='/';" type="button" value="Back" />
      <input tabindex="2" class="btnSendForgPass btn btnEasygoing" id="update" name="update" type="submit" value="Send new password">
   <form/>
</div>
