
<h1>Create an acount</h1>
		echo 	${affiche};
    <form method="POST" action="app?action=add" role="form" class="form-horizontal">
     <div class="form-group">
        <label class="control-label col-sm-2" for="username">Username *</label>
        <div class="col-sm-10">
           <input type="text" name="name" class="form-control"  required="required" />
        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="lastname">Last name </label>
        <div class="col-sm-10">
           <input type="text" name="lname" class="form-control" required="required" />

        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="firstname">First name </label>
        <div class="col-sm-10">
           <input type="text" name="fname" class="form-control" required="required" />
        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="password1">Password *</label>
        <div class="col-sm-10">
           <input type="password" name="password" class="form-control" required="required" />
        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="password2">Repeat Password *</label>
        <div class="col-sm-10">
           <input type="password" name="password2" class="form-control" required="required" />
        </div>
     </div>

     <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email </label>
        <div class="col-sm-10">
           <input type="email" name="mail" class="form-control" required="required" />
        </div>
     </div>
     <div>
       <label class="control-label col-sm-2" for="picture">Picture </label>
       <div>
        <input id="input-21" type="file" accept="image/*" class="file-loading">
          <script>
          $(document).on('ready', function() {
              $("#input-21").fileinput({
                  previewFileType: "image",
                  browseClass: "btn btn-success",
                  browseLabel: "Pick Image",
                  browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
                  removeClass: "btn btn-danger",
                  removeLabel: "Delete",
                  removeIcon: "<i class=\"glyphicon glyphicon-trash\"></i> ",
                  uploadClass: "btn btn-info",
                  uploadLabel: "Upload",
                  uploadIcon: "<i class=\"glyphicon glyphicon-upload\"></i> "
              });
          });
          </script>
       </div>
   </div>
   <div>
     <label class="checkbox-inline"><input type="checkbox" value="">Tutorial</label>
   </div>
   <div id = "btnCreate">
     <button class="btn btn-primary" type="submit">Create</button>
   </div>
</form>
