<script type="text/javascript">
   // Click on the right "Add Specialization" button when the user pressed the
   // 'Enter' key.
   // Parameters:
   //    - event: the event object renerated by the JQuery 'keypress' function.
   //    - context: represent the clicked text input.
   function pressNewSpecButton(event, context) {
      if (event.which == 13) {
         // Prevent form sending.
         event.preventDefault();
         // Click on the right button.
         $("#newSpecButton" + $(context).attr("id-spec")).click();
         return false;
      }
   }

   // Add a new specialization field right after the current one.
   // Parameters:
   //    - currentId: the current specialization field's ID.
   function addNewSpec(currentId) {
      // Maximum number of specializations.
      const MAX_FIELDS = 5;
      // Calculate new specialization field's ID.
      var newId = currentId + 1;

      // Check that there is not already 5 specialization (maximum), that the new
      // specialization field is not already existing and that the user entered a
      // value in the current specialization field.
      if (currentId < MAX_FIELDS && !$("#specialization" + newId).length && $("#txtSpecialization" + currentId).val()) {
         var newSpecDiv =
            '<div class="form-group" id="specialization' + newId + '">\
              <label class="control-label col-sm-2" for="name">Specialization ' + newId + '</label>\
              <div class="col-sm-10">';

         // Add a "New specialization" button only if thery is not the last possible specialization.
         if (newId < MAX_FIELDS) {
            newSpecDiv +=
                  '<div class="input-group">\
                    <input class="form-control" id="txtSpecialization' + newId + '" id-spec="' + newId + '" maxlength=50 placeholder="Enter specialization (e.g. \'Database Manager\')"\
                          name="specialization' + newId + '" type="text" />\
                   <span class="input-group-addon newSpecButton" data-toggle="tooltip" id="newSpecButton' + newId + '" title="Add a new specialization..." onClick="addNewSpec(' + newId + ');">\
                     <img class="newSpecImg" id="newSpecImg' +  newId + '" src="/img/plus.svg" />\
                   </span>';
         }
         else {
            newSpecDiv +=
                  '<input class="form-control" id="txtSpecialization' + newId + '" id-spec="' + newId + '" placeholder="Enter specialization"\
                       name="specialization' + newId + '" type="text" />';
         }

         newSpecDiv +=
               '</div>\
              </div>\
            </div>';

         // Insert the new specialization field right after the current one.
         $("#specialization" + currentId).after(newSpecDiv);

         // Add a keypress function on the new field (only if it is not the last).
         if (newId < MAX_FIELDS) {
            $('#txtSpecialization' + newId).keypress(function (event) {
               pressNewSpecButton(event, this);
            });
            // Init Bootstrap's tooltip on 'Add specialization' buttons.
            $('[data-toggle="tooltip"]').tooltip();
         }
         // Focus the new field.
         $("#txtSpecialization" + newId).focus();
      }
      // If the current field is empty, indicate it to the user.
      else if (!$("#txtSpecialization" + currentId).val()) {
         // Hide other opened tooltips.
         $("input[id^='txtSpecialization'").tooltip("hide");

         // Add a tooltip on the field, and focus it.
         $("#txtSpecialization" + currentId).attr("data-toggle", "tooltip");
         $("#txtSpecialization" + currentId).attr("data-trigger", "manual");
         $("#txtSpecialization" + currentId).attr("title", "You have to enter a specialization before adding another one, or press the 'Create!' button if you don't want to have specialization.");
         $("#txtSpecialization" + currentId).tooltip("show");
         $("#txtSpecialization" + currentId).focus();

         // Hide specialization field's tooltip when the user unfocus it.
         $("#txtSpecialization" + currentId).blur(function() {
            $(this).tooltip("hide");
         });
      }
   }

   $(document).ready(function() {
      $("#projectStartDate").datepicker({format: 'yyyy-mm-dd', autoclose:true});
      $("#projectDeadline").datepicker({format: 'yyyy-mm-dd', autoclose:true});

      // Init Bootstrap's tooltip on 'Add specialization' buttons.
      $('[data-toggle="tooltip"]').tooltip();

      // Click on the "Add Specialization" button when the user pressed the
      $('#txtSpecialization1').keypress(function (event) {
         pressNewSpecButton(event, this);
      });
   });
</script>

<h1 class="pageTitle">Create a new project</h1>

<?php
   // if there was an error when creating the posted project, display it.
   if (isset($error))
   {
?>
      <div class="panel panel-danger error">
         <div class="panel-heading">
            <?php
               switch($error)
               {
                  case "errorFieldEmpty":
                     echo "Please fill all mandatory fields.";
                     break;
                  case "errorDate":
                     echo "Please enter a correct date format (YYYY-MM-DD) and check that the <b>From</b> date is lesser than the <b>To</b> one.";
                     break;
                  case "errorLogoSize":
                     echo "The logo you're trying to upload is too large, please retry.";
                     break;
                  case "errorLogoType":
                  case "errorLogoExtension":
                     echo "Please upload a file, which extension is allowed.";
                     break;
                  case  "errorLogo":
                     echo "Something is wrong with the file you're trying to upload, please retry.";
                     break;
                  case  "errorFilesUpload":
                     echo "Something wrong happend when uploading the logo, please retry.";
                     break;
                  case  "errorDatabaseAdding":
                     echo "Something wrong happend when creating the project, please retry.";
                     break;
                  default:
                     echo "An error occured, please retry.";
                     break;
               }
            ?>
         </div>
      </div>
<?php
   }
?>

<!-- 'enctype' attribut is used for posting pictures. -->
<form action="/projects/add" class="form-horizontal" enctype="multipart/form-data" method="POST" role="form">
    <div class="form-group">
        <label class="control-label col-sm-2" for="name">Name *</label>
        <div class="col-sm-10">
            <input class="form-control" id="projectName" maxlength=50 placeholder="Enter name"
                   name="name" required="required" type="text"
                   value="<?php if (isset($name)) echo $this->escapeHtml($name); ?>" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="description">Description</label>
        <div class="col-sm-10">
            <textarea class="form-control projectDescription" id="projectDescription" placeholder="Enter description"
                      name="description" rows=6><?php if (isset($description)) echo $this->escapeHtml($description); ?></textarea>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="startDate">Duration *</label>
        <div class="col-sm-10">
            <p>
                From
                <input class="form-control" id="projectStartDate" placeholder="YYYY-MM-DD"
                       name="startDate" required="required" type="date"
                       value="<?php if (isset($startDate)) echo $this->escapeHtml($startDate); ?>" />
            </p>
            <p>
                To
                <input class="form-control" id="projectDeadline" placeholder="YYYY-MM-DD"
                       name="deadline" required="required" type="date"
                       value="<?php if (isset($deadline)) echo $this->escapeHtml($deadline); ?>" />
            </p>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="logo">Logo</label>
        <div class="col-sm-10">
            <p class="logoInformation">Priorize a <b>squared</b> logo - Maximum size of <b>5 MB</b> - Allowed extensions: <b>"jpeg", "jpg" or "png"</b>.</p>
            <input type="hidden" name="MAX_FILE_SIZE" value="5242880" />
            <input id="projectLogo" name="logo" type="file" />
        </div>
    </div>

    <hr/>

    <h4 class="specTitle">Okay one more thing: what are your specializations in this project (maximum of <b>5</b>)?</h4>
    <div class="form-group" id="specialization1">
      <label class="control-label col-sm-2" for="name">Specialization 1</label>
      <div class="col-sm-10">
         <div class="input-group">
           <input class="form-control" id="txtSpecialization1" id-spec="1" maxlength=50 placeholder="Enter specialization (e.g. 'Database Manager')"
                  name="specialization1" type="text"
                  value="<?php if (isset($specialization[0])) echo $this->escapeHtml($specialization[0]); ?>" />
           <span class="input-group-addon newSpecButton" data-toggle="tooltip" id="newSpecButton1" title="Add a new specialization..." onClick="addNewSpec(1);">
             <img class="newSpecImg" id="newSpecImg1" src="/img/plus.svg" />
           </span>
        </div>
      </div>
    </div>

    <div class="form-group formSending">
        <label class="control-label col-sm-2" for="logo"></label>
        <div class="col-sm-10">
            <span class="mandatoryFields">* Mandatory fields</span>
            <input class="btnCreate btn btnEasygoing" id="addProject" name="submit" type="submit" value="Create!" />
            <input class="btnCancel btn btnEasygoing" id="cancel" name="cancelButton" onClick="location.href='/projects';" type="button" value="Cancel" />
        </div>
    </div>
</form>
