<script type="text/javascript">
    try {
        loadTutorial("projects");
    }
    catch(err) {
        // Catch to avoid undefined loadTutorial error if user doesn't want tutorial
    }
</script>

<script type="text/javascript">
<!--
    var currentSelected;
    var isSelectionChanging = false;
    var isAjaxRequestComplete = false;

    $(document).ready(function() {
      // Init Bootstrap's tooltip on project's buttons.
      $('[data-toggle="tooltip"]').tooltip();

      // When the "Edit project" button is clicked, we don't need to display task's
      // details so we stop the propagation of the click event.
      $("#gotoLink, #gotoImg, #editLink, #editImg").click(function(e) {
         e.stopPropagation();
         // For IE.
         window.event.cancelBubble = true
      })
    })

    // Show the expand arrow image on an element identified by the given ID.
    function showExpandArrow(id)
    {
        if (currentSelected != id)
        {
            $("#expandArrow" + id).show();
        }
    }

    // Hide the expand arrow image on an element identified by the given ID.
    function hideExpandArrow(id)
    {
        if (currentSelected != id)
        {
            $("#expandArrow" + id).hide();
        }
    }

    // Display the given project's details.
    function displayProjectDetails(details, members)
    {
        // Clear the members table.
        // We have to select the elements inside the "projectDetails" row, otherwise
        // it would be possible to select an element of "oldProjectDetails" one.
        $("#projectDetails #membersTable tr").not("#membersTableHeader").remove();

        // Add each member in the members table.
        members.forEach(function(m) {
            var tableContent =
                "<tr>\
                    <td>" + m.username + "</td>\
                    <td>\
                       <ul class='specializationsList'>";

            // Add each member's specialization in the table's cell.
            m.specializations.forEach(function(s) {
               if (s != "-") {
                  tableContent += "<li>" + s + "</li>";
               }
               // If there is no specialization, don't display a list.
               else {
                  tableContent += s;
               }
            });

            tableContent +=
                      "</ul>\
                    </td>\
                    <td class='checkboxManager'>\
                        <input " + (m.isAdmin ? "checked " : "") + "type='checkbox' name='chkManager' value='Manager' disabled='disabled'>\
                    </td>\
                    </td>\
                </tr>";

            // Insert the new row right after the last one.
            $("#projectDetails #membersTable tr:last").after(tableContent);
        });

        // Display project's details.
        $("#projectDetails #txtName").val(details.name);
        $("#projectDetails #txtDescription").text(details.description);
        $("#projectDetails #txtStartDate").val(details.startDate);
        $("#projectDetails #txtDeadline").val(details.deadLineDate ? details.deadLineDate : "-");
    }

    // Expend or collapse the project identified by the given ID.
    // We can expect a few cases :
    //    1. If the function is currently executed, when just exit it.
    //    2. If the given ID corresponds to the currently selected project, we
    //       collapse it and then exit.
    //    2. If no other project is currently selected, we just slide down the
    //       project's properties.
    //    3. If another project is currently selected, we slide it up as the
    //       time that we are sliding down the new selected one.
    function expandProject(id, details, members)
    {
        // If there was no AJAX request before the calling, when just exit.
        if (isAjaxRequestComplete)
        {
            // Reset previous selected element.
            $("#project" + currentSelected).attr("class", "projectLine");
            $("#collapseArrow" + currentSelected).hide();

            // Check if the given ID is not corresponding to the current selected
            // project.
            if (currentSelected != id)
            {
                // Set new selected element properties.
                $("#project" + id).attr("class", "projectLineSelected");
                $("#projectLink").attr("href", "/project/" + id);
                $("#expandArrow" + id).hide();
                $("#collapseArrow" + id).show();

                // If another project is currently selected, we slide it up.
                // We use a "trick" to slide it up the old selected project as
                // the same time as we're sliding down the new selected one : we
                // clone the old object to allowing the two elements to be
                // displayed at the same time.
                if (currentSelected)
                {
                    // First rename the old selected element.
                    $("#projectDetails").attr("id", "oldProjectDetails");
                    // Then clone it and move the new clone right after the
                    // selected projects' table's row.
                    $("#project" + id).after($("#oldProjectDetails").clone().attr("id", "projectDetails").hide());

                    // Slide up the old element and remove it definitly when the
                    // action finish.
                    $("#oldProjectDetails #divProjectDetails").slideUp("fast", function() {
                        $("#oldProjectDetails").remove();
                        // Indicate the system that the function finished.
                        isSelectionChanging = false;
                        isAjaxRequestComplete = false;
                    });
                }

                currentSelected = id;

                // Display project's details.
                displayProjectDetails(details, members);

                // Move the details row right after the selected projects'
                // table's row and then slide it down.
                $("#project" + id).after($("#projectDetails"));
                $("#projectDetails").show();
                $("#divProjectDetails").slideDown("fast", function() {
                    // Indicate the system that the function finished.
                    isSelectionChanging = false;
                    isAjaxRequestComplete = false;
                });
            }
        }
    }

    // Load the given project's details with AJAX, and send them to the "expandProject"
    // function.
    function loadProjectDetails(id)
    {
        // If the function is currently executed, when just exit it.
        if (!isSelectionChanging)
        {
            // If the user just want to collapse the expanded selected project,
            // We don't want to make an AJAX request.
            if (currentSelected != id)
            {
                // Indicate the system that this function is currently executed. In
                // other words, we are indicating that we are in a critical section,
                // because we cannot have to projects which are loadind simultaneously.
                isSelectionChanging = true;

                // Make an AJAX GET request to the ProjectController to get back
                // all selected project information.
                // We expect to receive back JSON as a response.
                $.ajax({
                    type: "GET",
                    url:  "/project/" + id + "/details",
                    dataType: 'json',
                    // Occurs when the AJAX request was successfully executed.
                    success: function (data)
                    {
                        // In case of success, we send back the data to the expandProject()
                        // function.
                        if(data.success)
                        {
                            isAjaxRequestComplete = true;
                            expandProject(id, data.projectDetails, data.members);
                        }
                    },
          			  error: function (XMLHttpRequest, textStatus, errorThrown) {
          					alert("An error occured, please retry.");
                        isSelectionChanging = false;
          			  }
                 });
             }
             // If the user clicked to the currently selected project, we
             // just slide it up.
             else
             {
                 isSelectionChanging = true;

                 // Reset previous selected element.
                 $("#project" + currentSelected).attr("class", "projectLine");
                 $("#collapseArrow" + currentSelected).hide();

                 $("#expandArrow" + currentSelected).show();
                 currentSelected = undefined;

                 $("#divProjectDetails").slideUp("fast", function() {
                     $("#projectDetails").hide();
                     // Indicate the system that the function finished.
                     isSelectionChanging = false;
                 });
             }
         }
    }

    // Search for a project when the user types in the search field.
    function filterSearch()
    {
       var text = $('#search').val();

       // For each tr in table...
       $.each($('#tableListProjects'), function(i, table)
       {
          $('tr[name="projectLine"]', table).each(function(i, tr)
          {
             if($(tr).attr('title').indexOf(text) > -1)
             {
                $(tr).show("fast");
            }
             else
             {
                // If the project-to-hide is currently selected, close the details
                // row.
                if ($(tr).attr("class") === "projectLineSelected")
                {
                    isSelectionChanging = true;

                    // Reset previous selected element.
                    $("#project" + currentSelected).attr("class", "projectLine");
                    $("#collapseArrow" + currentSelected).hide();

                    currentSelected = undefined;

                    $("#projectDetails").hide("fast");
                    // Indicate the system that the function finished.
                    isSelectionChanging = false;
                }

                $(tr).hide("fast");
            }
          });
      });
    }
-->
</script>

<table class="projectsHeaderTable">
    <tr>
        <td><h1 class="projectsTitle">Your projects</h1></td>
        <td>
             <a class="newProject" href="/projects/add">
             <b>Create a new project !</b><img class="newProjectImg" src="/img/plus.svg" /></a>
        </td>
        <td><div id="createProject" role="tutorial" data-placement="bottom"></div></td>
    </tr>
</table>

<?php
	if (sizeof($userProjects) > 0)
	{
?>
        <table class="projectsToolsTable">
            <tr>
                <td>Click on a project to see details.</td>
                <div id="searchProject" role="tutorial"></div>
                <td><input onkeyup="filterSearch();" type="text" id="search" class="form-control" placeholder="Search for..." /></td>
            </tr>
        </table>

        <div id="listOfProjects" role="tutorial"></div>

        <table id="tableListProjects" class="tableListProjects">
    <?php
        foreach ($userProjects as $p) :
    ?>
            <tr name="projectLine" id="project<?php echo $p->id; ?>" class="projectLine"
                onMouseOver="showExpandArrow(<?php echo $p->id; ?>);"
                onMouseOut="hideExpandArrow(<?php echo $p->id; ?>);"
                onClick="loadProjectDetails(<?php echo $p->id; ?>);"
                title="<?php echo $this->escapeHtml($p->name); ?>">
                <td class="projectTitle">
                    <img src="<?php echo $this->basePath('img/projects/' . $p->fileLogo); ?>"
                         alt="<?php echo $this->escapeHtml($p->name); ?>" height=50 width=50
                         class="imgProject" />
                    <?php echo $this->escapeHtml($p->name); ?>
                </td>
                <td class="expandArrow">
                    <img id="expandArrow<?php echo $p->id; ?>"
                         src="<?php echo $this->basePath('img/expand.png'); ?>"
                         alt="Expand project <?php echo $this->escapeHtml($p->name); ?>"
                         height=50 />
                    <img id="collapseArrow<?php echo $p->id; ?>"
                         src="<?php echo $this->basePath('img/collapse.png'); ?>"
                         alt="Collapse project <?php echo $this->escapeHtml($p->name); ?>"
                            height=50 />
                </td>
                <td class="rightProjectTd">
                  <?php if($p->creator == $userId) : ?>
                     <img class="managerIcon" data-toggle="tooltip" title="You are the creator and super administrator of this project." src="/img/creator.svg" />
                  <?php endif; ?>

                  <?php
                     if ($p->isAdmin)
                     {
                  ?>
                        <img class="managerIcon" data-toggle="tooltip" title="You are manager of this project." src="/img/manager.svg" />
                        <a class="projectLink" href="/project/<?php echo $p->id; ?>/edit" id="editLink"><img class="editProjectIcon" data-toggle="tooltip" id="editImg" title="Edit the project..." src="/img/edit.svg" /></a>
                  <?php
                     }
                  ?>
                  <a class="projectLink" href="/project/<?php echo $p->id; ?>" id="gotoLink"><img class="gotoIcon" data-toggle="tooltip" id="gotoImg" title="Click here to see your project's progression." src="/img/goto.svg" /></a>
                </td>
            </tr>
    <?php
        endforeach;
    ?>
            <tr id="projectDetails" class="projectDetails">
                <td colspan=3>
                    <div id="divProjectDetails" class="divProjectDetails">
                        <form role="form" class="form-horizontal">
                            <div class="form-group formProjectDetails">
                                <label class="control-label col-sm-2" for="name">Full name</label>
                                <div class="col-sm-10">
                                    <input class="projectName" disabled="disabled" id="txtName" name="name" type="text" />
                                </div>
                            </div>

                            <div class="form-group formProjectDetails">
                                <label class="control-label col-sm-2" for="description">Description</label>
                                <div class="col-sm-10">
                                    <textarea id="txtDescription" name="description" class="form-control projectDescriptionInList" disabled="disabled" rows=6></textarea>
                                </div>
                            </div>

                            <div class="form-group formProjectDetails">
                                <label class="control-label col-sm-2" for="members">Members</label>
                                <div class="col-sm-10">
                                    <table class="membersTable" id="membersTable" name="members">
                                        <tr id="membersTableHeader">
                                            <th>Name</th>
                                            <th>Specializations</th>
                                            <th>Manager</th>
                                        </tr>
                                    </table>
                                </div>
                            </div>

                            <div class="form-group formProjectDetails">
                                <label class="control-label col-sm-2" for="duration">Duration</label>
                                <div class="col-sm-10">
                                    <p>
                                        From<br/>
                                        <input disabled="disabled" id="txtStartDate" name="txtStartDate" type="text" />
                                    </p>
                                    <p>
                                        To<br/>
                                        <input disabled="disabled" id="txtDeadline" name="txtBeginDate" type="text" />
                                    </p>
                                    <div class="linkToProject"><a id="projectLink" href="/project/">Click here to see your project's progression.</a></div>
                                </div>
                            </div>
                        </form>
                    </div>
                </td>
            </tr>
        </table>
<?php
    }
    else
    {
        echo "You are not member of a project yet.";
    }
 ?>
